<a href="https://colab.research.google.com/github/GiacomoDiFa/Progetto-MN/blob/main/provamatrice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np

n = 7  # Numero di righe
m = 11  # Numero di colonne
h = 1./(n-1)
print(h)
print(12*(h**2))
# Creazione della matrice con diagonali
matrix = np.zeros((n, m))  # Inizializza una matrice di zeri

# Assegna valori alla diagonale principale
a = -1
b = 16
c = -30
main_diagonal = np.full(min(n, m), a)
np.fill_diagonal(matrix, main_diagonal)

# Assegna valori alle altre diagonali sopra e sotto la diagonale principale


np.fill_diagonal(matrix[:, 1:], b)
np.fill_diagonal(matrix[:, 2:], c)
np.fill_diagonal(matrix[:, 3:], b)
np.fill_diagonal(matrix[:, 4:], a)

print(matrix)

0.16666666666666666
0.3333333333333333
[[ -1.  16. -30.  16.  -1.   0.   0.   0.   0.   0.   0.]
 [  0.  -1.  16. -30.  16.  -1.   0.   0.   0.   0.   0.]
 [  0.   0.  -1.  16. -30.  16.  -1.   0.   0.   0.   0.]
 [  0.   0.   0.  -1.  16. -30.  16.  -1.   0.   0.   0.]
 [  0.   0.   0.   0.  -1.  16. -30.  16.  -1.   0.   0.]
 [  0.   0.   0.   0.   0.  -1.  16. -30.  16.  -1.   0.]
 [  0.   0.   0.   0.   0.   0.  -1.  16. -30.  16.  -1.]]


In [17]:
n1 = 2
m1 = 11
matrix1 = np.zeros((n1,m1))
a1 = -2
b1 = 1
main_diagonal1 = np.full(min(n1,m1),a1)
np.fill_diagonal(matrix1,main_diagonal1)
np.fill_diagonal(matrix1[:,1:],b1)
np.fill_diagonal(matrix1[-1:,:],b1)
print(matrix1)

[[-2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [31]:
n2 = 2
m2 = 11
matrix2 = np.zeros((n2,m2))
a2 = -2
b2 = 1
np.fill_diagonal(matrix2[:,-1:],b2)
np.fill_diagonal(matrix2[:,-2:],a2)
np.fill_diagonal(matrix2[:,-3:],b2)
print(matrix2)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  1. -2.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -2.]]


In [55]:
nfin = 11
mfin = 11
A = np.pad(matrix1, ((0, nfin-matrix1.shape[0]), (0, mfin-matrix1.shape[1])), mode='constant')
B = np.pad(matrix2, ((nfin-matrix2.shape[0], 0), (0, mfin-matrix2.shape[1])), mode='constant')
pad_rows = (nfin - matrix.shape[0]) // 2
pad_cols = (mfin - matrix.shape[1]) // 2
C = np.pad(matrix, (((pad_rows, nfin - matrix.shape[0] - pad_rows), (pad_cols, mfin - matrix.shape[1] - pad_cols))), mode='constant')
D = A+B+C
print(A)
print("")
print(B)
print("")
print(C)
print("")
print(D)
D[0,0] = 1
D[-1,-1] = 1
D[0,1] = 0
D[-1,-2] = 0
print("")
print(D)

[[-2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1. -2.  1.]
 [ 0.  0.  

In [71]:
m = 14 #numero di colonne
n = m-4  # Numero di righe
h = 1./(n-1)
print(h)
print(12*(h**2))
# Creazione della matrice con diagonali
matrix = np.zeros((n, m))  # Inizializza una matrice di zeri

# Assegna valori alla diagonale principale
a = -1
b = 16
c = -30
main_diagonal = np.full(min(n, m), a)
np.fill_diagonal(matrix, main_diagonal)

# Assegna valori alle altre diagonali sopra e sotto la diagonale principale


np.fill_diagonal(matrix[:, 1:], b)
np.fill_diagonal(matrix[:, 2:], c)
np.fill_diagonal(matrix[:, 3:], b)
np.fill_diagonal(matrix[:, 4:], a)

print(matrix)

0.1111111111111111
0.14814814814814814
[[ -1.  16. -30.  16.  -1.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  -1.  16. -30.  16.  -1.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  -1.  16. -30.  16.  -1.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  -1.  16. -30.  16.  -1.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  -1.  16. -30.  16.  -1.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  -1.  16. -30.  16.  -1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  -1.  16. -30.  16.  -1.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  -1.  16. -30.  16.  -1.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  -1.  16. -30.  16.  -1.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  -1.  16. -30.  16.  -1.]]


In [109]:
def finDif(omega,f,n,bc):
  x = np.linspace(0,np.pi,n)
  terminenoto = f(x)
  print(terminenoto)
  print("")
  h = 1./(n-1)
  m = n + 4 #numero di colonne matrice
  matrix = np.zeros((n, m))  # Inizializza una matrice di zeri
  # Assegna valori alla diagonale principale
  a = -1
  b = 16
  c = -30
  main_diagonal = np.full(min(n, m), a)
  np.fill_diagonal(matrix, main_diagonal)
  # Assegna valori alle altre diagonali sopra e sotto la diagonale principale
  np.fill_diagonal(matrix[:, 1:], b)
  np.fill_diagonal(matrix[:, 2:], c)
  np.fill_diagonal(matrix[:, 3:], b)
  np.fill_diagonal(matrix[:, 4:], a)
  #matrix /= 12*h**2
  print(matrix)
  print("")
  
  d = -2
  e = 1
  r = 2
  
  matrix1 = np.zeros((r,m))
  main_diagonal1 = np.full(min(r,m),d)
  np.fill_diagonal(matrix1,main_diagonal1)
  np.fill_diagonal(matrix1[:,1:],e)
  np.fill_diagonal(matrix1[-1:,:],e)
  #matrix1 /= h**2
  print(matrix1)
  print("")

  
  matrix2 = np.zeros((r,m))
  np.fill_diagonal(matrix2[:,-1:],e)
  np.fill_diagonal(matrix2[:,-2:],d)
  np.fill_diagonal(matrix2[:,-3:],e)
  #matrix2 /= h**2
  print(matrix2)
  print("")


 
  A = np.pad(matrix1, ((0, m-matrix1.shape[0]), (0, m-matrix1.shape[1])), mode='constant')
  B = np.pad(matrix2, ((m-matrix2.shape[0], 0), (0, m-matrix2.shape[1])), mode='constant')
  pad_rows = (m - matrix.shape[0]) // 2
  pad_cols = (m - matrix.shape[1]) // 2
  C = np.pad(matrix, (((pad_rows, m - matrix.shape[0] - pad_rows), (pad_cols, m - matrix.shape[1] - pad_cols))), mode='constant')
  D = A+B+C
  print(A)
  print("")
  print(B)
  print("")
  print(C)
  print("")
  print(D)
  print("")
  D[0,0] = 1
  D[-1,-1] = 1
  D[0,1] = 0
  D[-1,-2] = 0
  print("")
  print(D)
  print("")
  terminenoto[0] = bc[0]
  terminenoto[-1] = bc[1]
  print(terminenoto)
  print("")





omega = [0,np.pi]
f = lambda x : np.sin(x)
n=7
bc = [0,0]
finDif(omega, f, n, bc)
#unica cosa che non mi viene in mente adesso è che se io voglio 7 iterazioni (n) mi viene fuori matrice 11x11. 
#non dovrebbe essere 7x7?
#l'ho fatta venire 11 per 11 per come viene passato il parametro nella funzione, ma non so se come significato "fisico"
#abbia senso che io metto n=7 e torni una matrice 11x11
#la matrice finale è D
#no non torna anche perchè il termine noto b viene di 7 elementi giustamente
#potrei farlo tornare passandogli m nel linspace però non credo abbia senso a livello "fisico"
#ricordarsi di scommentare le divisioni una volta finito il codice 

[0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]

[[ -1.  16. -30.  16.  -1.   0.   0.   0.   0.   0.   0.]
 [  0.  -1.  16. -30.  16.  -1.   0.   0.   0.   0.   0.]
 [  0.   0.  -1.  16. -30.  16.  -1.   0.   0.   0.   0.]
 [  0.   0.   0.  -1.  16. -30.  16.  -1.   0.   0.   0.]
 [  0.   0.   0.   0.  -1.  16. -30.  16.  -1.   0.   0.]
 [  0.   0.   0.   0.   0.  -1.  16. -30.  16.  -1.   0.]
 [  0.   0.   0.   0.   0.   0.  -1.  16. -30.  16.  -1.]]

[[-2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]

[[ 0.  0.  0.  0.  0.  0.  0.  0.  1. -2.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -2.]]

[[-2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.